export const governmentTypeValues = [
  "DEMOCRACY",
  "REPUBLIC",
  "MONARCHY",
  "DICTATORSHIP",
  "COUNCIL",
  "THEOCRACY",
  "DEMOCRATIC_REPUBLIC",
  "CONSTITUTIONAL_MONARCHY",
  "FEDERAL_UNION",
  "SOCIALIST_REPUBLIC",
  "TECHNOCRACY",
  "MILITARY_DIRECTORATE",
  "CORPORATE_STATE",
  "TRIBAL_CONFEDERATION",
  "CITY_STATE_LEAGUE"
] as const;
export const economyTypeValues = [
  "MIXED",
  "MARKET",
  "PLANNED",
  "SUBSISTENCE",
  "COMMAND",
  "MIXED_MARKET",
  "PLANNED_ECONOMY",
  "FREE_MARKET",
  "RESOURCE_EXTRACTION",
  "AGRARIAN",
  "INDUSTRIAL",
  "POST_INDUSTRIAL",
  "COMMAND_ECONOMY",
  "TRADE_BASED",
  "TECHNOLOGICAL"
] as const;
export const foundingOriginValues = [
  "OLD_KINGDOM",
  "REVOLUTIONARY_REPUBLIC",
  "COLONIAL_SUCCESSOR",
  "FRONTIER_SETTLEMENT",
  "MERCHANT_LEAGUE",
  "MILITARY_JUNTA",
  "SPIRITUAL_COMMONWEALTH",
  "INDUSTRIAL_UNION",
  "TECHNOCRATIC_PROJECT",
  "NOMADIC_CONFEDERATION"
] as const;
export const nationPostTypeValues = ["NEWS", "SPEECH", "GOVERNMENT_UPDATE", "IMAGE", "VIDEO"] as const;
export const postVisibilityValues = ["PUBLIC", "PRIVATE", "DRAFT"] as const;
export const agentAssignmentValues = ["IDLE", "GOVERNING", "COMMANDING", "GUARDING", "SPEAKING", "IMPROVING"] as const;
